server:
  port: 80
spring:
  application:
    name: spzx-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.123:8848
    gateway:
      routes:
        - id: spzx-cloud-order				# 路由id，可以自定义，只要唯一即可
          uri: lb://spzx-cloud-order		    # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/*/order/**			    # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: spzx-cloud-user				# 路由id，可以自定义，只要唯一即可
          uri: lb://spzx-cloud-user		    # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/*/user/**